# Generated by Django 3.2.4 on 2021-06-20 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
                ('price', models.IntegerField()),
                ('description', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'products',
            },
        ),
    ]
